disabled_rules:
  - identifier_name # Variable names with less than 3 characters don't warn
  - multiple_closures_with_trailing_closure # Needed for SwiftUI syntax

opt_in_rules:
  - empty_count # Prefer .isEmpty for collections
  - empty_string # Prefer .isEmpty for strings
  - fatal_error_message # Fatal errors need a message
  - first_where # Prefer .first(where: ) over .filter{ }.first
  - modifier_order # Set order of public, final, etc
  - toggle_bool # Prefer .toggle() over myBool = !myBool

