name: Swift

on:
  push:
  pull_request:
    branches: [ master ]
  schedule:
    # Nightly builds at midnight
    - cron: 0 0 * * *
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v --enable-code-coverage
      
    - name: Export environment variables
      run: echo "::set-output name=CODE_COVERAGE_REPORT_PATH::$(swift test --show-codecov-path)"
      id: env
      
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        file: ${{ steps.env.outputs.CODE_COVERAGE_REPORT_PATH }}
        dry_run: true
        verbose: true
